use_frameworks!

platform :ios, '10.0'

target 'submission-Detail_Example' do
  pod 'submission-Detail', :path => '../'

  target 'submission-Detail_Tests' do
    inherit! :search_paths

    
  end
end
